Fix downstream ChromeOS build bot
After rolling FFMPEG, a downstream ChromeOS bot broke due to being
strict about not allowing macro redefinitions in Chrome. An example
test failure:

https://ci.chromium.org/ui/p/chromium/builders/ci/chromeos-arm-generic-dbg/122416/overview

```
../../third_party/ffmpeg/libavutil/arm/cpu.c:50:9: error: 'HWCAP_ARM_VFP' macro redefined [-Werror,-Wmacro-redefined]
   50 | #define HWCAP_ARM_VFP     (1 << 6)
      |         ^
../../build/cros_cache/chrome-sdk/symlinks/arm-generic+16489.0.0-1073269+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/bits/hwcap.h:30:9: note: previous definition is here
   30 | #define HWCAP_ARM_VFP           64
      |         ^
../../third_party/ffmpeg/libavutil/arm/cpu.c:51:9: error: 'HWCAP_ARM_EDSP' macro redefined [-Werror,-Wmacro-redefined]
   51 | #define HWCAP_ARM_EDSP    (1 << 7)
```

This patch fixes the issue by having ffmpeg compile with the macro
redefinition being allowed.

Bug: 450394710
Change-Id: I10ea176b290373ad8c6cfa30b5282c80b7af27d3
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/third_party/ffmpeg/+/7181687
Reviewed-by: Ted (Chromium) Meyer <tmathmeyer@chromium.org>
Reviewed-by: Thomas Guilbert <tguilbert@chromium.org>